//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPasswordLibrary.CommandLine.DnMPlus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACPasswordLibrary.CommandLine.DnMPlus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000	spooky wardrobe
        ///1004	classic wardrobe
        ///1008	blue wardrobe
        ///100C	office locker
        ///1010	Jingle wardrobe
        ///1014	regal armoire
        ///1018	cabana wardrobe
        ///101C	cabin wardrobe
        ///1020	lovely armoire
        ///1024	green wardrobe
        ///1028	pear wardrobe
        ///102C	ranch wardrobe
        ///1030	blue cabinet
        ///1034	modern wardrobe
        ///1038	exotic wardrobe
        ///103C	Jingle dresser
        ///1040	regal dresser
        ///1044	cabana dresser
        ///1048	cabin dresser
        ///104C	lovely dresser
        ///1050	spooky dresser
        ///1054	green dresser
        ///1058	pear dresser
        ///105C	ranch dresser
        ///1060	classic  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AF_Item_List {
            get {
                return ResourceManager.GetString("AF_Item_List", resourceCulture);
            }
        }
    }
}
