//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACPasswordLibrary.CommandLine.AnimalCrossing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACPasswordLibrary.CommandLine.AnimalCrossing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0000, Empty
        ///0x0001, Tree Stump (Small)
        ///0x0002, Tree Stump (Medium)
        ///0x0003, Tree Stump (Large)
        ///0x0004, Tree Stump (Fully Grown)
        ///0x0005, Fence (Type 1)
        ///0x0006, Fence (Type 2)
        ///0x0007, Message Board (B)
        ///0x0008, Weed
        ///0x0009, Weed
        ///0x000A, Weed
        ///0x000B, Message Board (A)
        ///0x000C, Map Board (B)
        ///0x000D, Map Board (A)
        ///0x000E, Music Board (B)
        ///0x000F, Music Board (A)
        ///0x0010, Wooden Fence
        ///0x0011, Hole
        ///0x0012, Hole (Angled Down)
        ///0x0013, Hole (Angled Up)
        ///0x0014, Hole (Angled Right)
        ///0x0015, Hole (Angle [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AC_Items_en {
            get {
                return ResourceManager.GetString("AC_Items_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0x0000, No Villager
        ///0xE000, Bob
        ///0xE001, Olivia
        ///0xE002, Mitzi
        ///0xE003, Kiki
        ///0xE004, Tangy
        ///0xE005, Kabuki
        ///0xE006, Tabby
        ///0xE007, Monique
        ///0xE008, Stinky
        ///0xE009, Purrl
        ///0xE00A, Kitty
        ///0xE00B, Tom
        ///0xE00C, Rosie
        ///0xE00D, Nosegay
        ///0xE00E, Zoe
        ///0xE00F, Pango
        ///0xE010, Cyrano
        ///0xE011, Snooty
        ///0xE012, Teddy
        ///0xE013, Chow
        ///0xE014, Dozer
        ///0xE015, Nate
        ///0xE016, Groucho
        ///0xE017, Tutu
        ///0xE018, Ursala
        ///0xE019, Grizzly
        ///0xE01A, Pinky
        ///0xE01B, Jay
        ///0xE01C, Twiggy
        ///0xE01D, Anchovy
        ///0xE01E, Piper
        ///0xE01F, Admiral
        ///0xE0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AC_Villagers_en {
            get {
                return ResourceManager.GetString("AC_Villagers_en", resourceCulture);
            }
        }
    }
}
